# Generated by Django 2.2.3 on 2019-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_remove_biography_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
