# Generated by Django 2.2.3 on 2019-07-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_project_projectlink_projecttag_skill_skilltarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='www.Local'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='www.Local'),
        ),
    ]
