# Generated by Django 2.2.3 on 2019-07-25 15:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20190725_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(to='www.Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='www.Tag'),
        ),
        migrations.AddField(
            model_name='skill',
            name='target',
            field=models.ManyToManyField(to='www.Target'),
        ),
    ]
