# Generated by Django 2.2.3 on 2019-07-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20190725_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='www.Local'),
        ),
    ]
