# Generated by Django 2.2.3 on 2019-07-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_auto_20190725_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='target',
            new_name='targets',
        ),
    ]
